import './globals.css';
import { Shippori_Mincho } from 'next/font/google';
import Layout from '@/components/layout';

const shippori = Shippori_Mincho({ subsets: ['latin'], weight: '500' });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={shippori.className}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
