'use client';

import './globals.css';
import { Inter } from 'next/font/google';
import adobeFonts from '@/api/adobe-fonts';
import { useEffect } from 'react';
import Layout from '@/components/layout';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  useEffect(() => {
    if (process.browser) adobeFonts(document);
  }, []);

  return (
    <html lang='en'>
      <body className={inter.className}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
