version: '3.3'
services:
  mysql:
    image: mysql:5.7 # MySQL のバージョンを指定
    container_name: db-for-umigame
    # MySQL の設定値を指定
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --sql-mode=ONLY_FULL_GROUP_BY,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
    # コンテナ内で使用する環境変数の値を指定
    environment:
      MYSQL_ROOT_USER: ${ROOTUSER} # MySQL のルートユーザー名
      MYSQL_ROOT_PASSWORD: ${ROOTPASS} # MySQL のルートユーザーのパスワード
      MYSQL_DATABASE: ${DATABASE} # MySQL に用意されている初期データベースの名前
      MYSQL_USER: ${USERNAME} # MySQL のユーザー名
      MYSQL_PASSWORD: ${USERPASS} # MySQL のユーザーパスワード
      TZ: 'Asia/Tokyo'
    # コンテナの ?? 番ポートを、ローカルの ?? 番ポートにつなげる
    ports:
      - "${DB_PORT}:${DB_PORT}"
    # コンテナ内にある MySQL に格納するデータを永続化させるために使用するボリュームを指定
    volumes:
      - db-volume:/var/lib/mysql
# ボリュームの作成
volumes:
  db-volume: